const STORAGE = 'motoroadbook-tour-v1';
const TYPES = { waypoint:'📍', drone:'🚁', photo:'📸', fuel:'⛽', lunch:'🍝', coffee:'☕' };
let tour, tours = [], activeTourId, map, routeLine, userMarker, watchId, lastPosition, alerted = new Set(), editingStopIndex = null;
const $ = s => document.querySelector(s);

async function init() {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE));
    if (saved?.tours) { tours=saved.tours; activeTourId=saved.activeTourId; }
    else { const initial=saved || await (await fetch('itinerari.json')).json(); initial.id=initial.id || crypto.randomUUID(); tours=[initial]; activeTourId=initial.id; }
    tour = tours.find(t=>t.id===activeTourId) || tours[0]; activeTourId=tour.id;
  } catch { tour = { id:crypto.randomUUID(), name:'Nuovo tour', departureTime:'08:30', stops:[] }; tours=[tour]; activeTourId=tour.id; }
  renderPlan(); bindEvents();
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js').catch(() => {});
}
function save() { tours=tours.map(t=>t.id===tour.id?tour:t); localStorage.setItem(STORAGE, JSON.stringify({activeTourId,tours})); renderPlan(); refreshMap(); }
function renderPlan() {
  if (!tour) { $('#tourName').textContent='Nessun tour programmato'; $('#tourMeta').textContent='Crea un tour o importane uno per iniziare.'; $('#tourList').innerHTML='<p class="hint">La tua libreria è vuota.</p>'; $('#stopsList').innerHTML=''; $('#openMaps').disabled=true; $('#deleteTour').disabled=true; return; }
  $('#openMaps').disabled=false; $('#deleteTour').disabled=false;
  $('#tourName').textContent = tour.name;
  $('#tourSubtitle').textContent = tour.date ? new Date(`${tour.date}T12:00`).toLocaleDateString('it-IT',{day:'numeric',month:'short'}) : 'Il tuo assistente di viaggio';
  $('#tourMeta').textContent = `Partenza prevista ${tour.departureTime || '—'} · ${tour.stops.length} punti in tabella`;
  $('#tourList').innerHTML=tours.map(t=>`<button class="tour-choice ${t.id===activeTourId?'active':''}" data-tour="${t.id}"><strong>${esc(t.name)}</strong><span>${t.date||'Data da definire'} · ${t.stops?.length||0} punti</span></button>`).join('');
  document.querySelectorAll('.tour-choice').forEach(b=>b.onclick=()=>{ activeTourId=b.dataset.tour; tour=tours.find(t=>t.id===activeTourId); alerted.clear(); renderPlan(); refreshMap(); });
  $('#stopsList').innerHTML = tour.stops.length ? tour.stops.map((s,i) => `<article class="stop-card"><div class="stop-time">${displayTargetTime(s.targetTime) || '—'}</div><div class="stop-icon">${TYPES[s.type] || '📍'}</div><div><div class="stop-title">${esc(s.name)}</div><span class="stop-sub">${s.durationMinutes ? `${s.durationMinutes} min · ` : ''}${esc(s.notes || typeName(s.type))}</span></div><button class="icon-button edit-stop" data-index="${i}" aria-label="Modifica ${esc(s.name)}">⋮</button></article>`).join('') : '<p class="hint">Aggiungi la prima tappa del tuo viaggio.</p>';
  document.querySelectorAll('.edit-stop').forEach(b => b.onclick = () => openStop(Number(b.dataset.index)));
}
function esc(v='') { const el=document.createElement('div'); el.textContent=v; return el.innerHTML; }
function openGoogleMaps() { if(tour?.googleMapsUrl) window.open(tour.googleMapsUrl,'_blank','noopener'); else toast('Aggiungi il link Google Maps nelle impostazioni del tour'); }
function autoImportGoogleStops(link) {
  if (!link || tour.stops.length) return 0;
  try {
    const url=new URL(link), names=[];
    const add=v=>{v=decodeURIComponent(v||'').replace(/\+/g,' ').trim();if(v&&v.length<120&&!names.includes(v))names.push(v)};
    add(url.searchParams.get('origin')); add(url.searchParams.get('destination'));
    (url.searchParams.get('waypoints')||'').split('|').forEach(add);
    const marker='/dir/'; const pos=url.pathname.indexOf(marker);
    if(pos>=0) url.pathname.slice(pos+marker.length).split('/').filter(p=>p&&!p.startsWith('@')&&!p.startsWith('data=')).forEach(add);
    names.forEach(name=>tour.stops.push({name,targetTime:'',durationMinutes:0,lat:null,lng:null,type:'waypoint',notes:'Importata dal link Google Maps. Aggiungi le coordinate per il rilevamento GPS.'}));
    return names.length;
  } catch { return 0; }
}
function typeName(t) { return ({waypoint:'Tappa',drone:'Spot drone',photo:'Foto panoramica',fuel:'Benzina',lunch:'Pranzo',coffee:'Caffè'})[t] || 'Tappa'; }
function openTour() { const f=$('#tourForm'); ['name','date','departureTime','googleMapsUrl'].forEach(k=>f.elements[k].value=tour[k]||''); $('#dialogLabel').textContent='MODIFICA TOUR'; $('#tourDialog').showModal(); }
function openStop(i=null) { editingStopIndex=i; const s=i===null?{durationMinutes:0,type:'waypoint'}:tour.stops[i]; const f=$('#stopForm'); ['name','targetTime','durationMinutes','lat','lng','type','notes'].forEach(k=>f.elements[k].value=s[k]??''); $('#stopDialogLabel').textContent=i===null?'NUOVO PUNTO':'MODIFICA PUNTO'; $('#deleteStop').hidden=i===null; $('#stopDialog').showModal(); }
function bindEvents() {
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
  $('#newTour').onclick=()=>{ tour={id:crypto.randomUUID(),name:'Nuovo tour in moto',date:'',departureTime:'08:30',googleMapsUrl:'',stops:[],completedStops:[]}; tours.push(tour); activeTourId=tour.id; save(); openTour(); };
  $('#addStop').onclick=()=>openStop(); $('#importTour').onclick=()=>$('#jsonDialog').showModal(); $('#openMaps').onclick=openGoogleMaps; $('#openMapsRide').onclick=openGoogleMaps;
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
  $('#tourForm').onsubmit=e=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(e.target)); Object.assign(tour,d); const imported=autoImportGoogleStops(d.googleMapsUrl); $('#tourDialog').close(); save(); toast(imported ? `${imported} tappe importate dal link` : 'Tour salvato'); };
  $('#stopForm').onsubmit=e=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(e.target)); d.durationMinutes=Number(d.durationMinutes)||0; d.lat=d.lat===''?null:Number(d.lat); d.lng=d.lng===''?null:Number(d.lng); if(editingStopIndex===null) tour.stops.push(d); else tour.stops[editingStopIndex]=d; $('#stopDialog').close(); save(); toast('Punto salvato'); };
  $('#deleteStop').onclick=()=>{ if(editingStopIndex===null)return; if(confirm(`Eliminare “${tour.stops[editingStopIndex].name}”?`)){tour.stops.splice(editingStopIndex,1);$('#stopDialog').close();save();toast('Tappa eliminata');} };
  $('#deleteTour').onclick=()=>{ if(!tour || !confirm(`Eliminare definitivamente il tour “${tour.name}”?`))return; tours=tours.filter(t=>t.id!==tour.id); tour=tours[0]||null; activeTourId=tour?.id||null; localStorage.setItem(STORAGE,JSON.stringify({activeTourId,tours})); renderPlan(); refreshMap(); toast('Tour eliminato'); };
  $('#jsonForm').onsubmit=e=>{ e.preventDefault(); try { let parsed=JSON.parse(new FormData(e.target).get('json')); if(Array.isArray(parsed)) parsed=parsed[0]; if(!parsed || !Array.isArray(parsed.stops)) throw Error('Manca la lista “stops”.'); tour={...parsed,id:crypto.randomUUID()}; tours.push(tour); activeTourId=tour.id; $('#jsonDialog').close(); save(); toast('Nuovo itinerario importato'); } catch(err) { $('#jsonError').textContent=`JSON non valido: ${err.message}`; } };
  $('#setDeparture').onclick=()=>{ $('#departureForm').elements.realTime.value=currentTime(); $('#departureDialog').showModal(); };
  $('#departureForm').onsubmit=e=>{ e.preventDefault(); tour.realDepartureTime=new FormData(e.target).get('realTime'); $('#departureDialog').close(); save(); updateHud(); toast('Tabella di marcia aggiornata'); };
  $('#centerMap').onclick=()=>{ if(lastPosition && map) map.setView([lastPosition.coords.latitude,lastPosition.coords.longitude],14); else startGPS(); };
  $('#fileInput').onchange=readFile; $('#exportTour').onclick=exportTour; $('#resetDemo').onclick=async()=>{ if(confirm('Ripristinare l’itinerario demo?')) { tour=await (await fetch('itinerari.json')).json(); tour.id=crypto.randomUUID(); tours=[tour]; activeTourId=tour.id; save(); } };
}
function switchView(view) { document.querySelectorAll('.mode-switch button').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); $('#planView').classList.toggle('active',view==='plan'); $('#rideView').classList.toggle('active',view==='ride'); if(view==='ride') { initMap(); setTimeout(()=>map?.invalidateSize(),100); startGPS(); updateHud(); } }
function initMap() { if(map) return refreshMap(); if(!window.L) { $('#mapFallback').textContent='Mappa non disponibile: apri una volta l’app con connessione per scaricare il modulo cartografico.'; return; } map=L.map('map',{zoomControl:false}).setView([46.5,11.83],10); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map); $('#mapFallback').remove(); refreshMap(); }
function refreshMap() { if(!map || !tour) return; if(routeLine) map.removeLayer(routeLine); const points=tour.stops.filter(s=>Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lng))).map(s=>[Number(s.lat),Number(s.lng)]); map.eachLayer(l=>{if(l.options?.poi)map.removeLayer(l)}); points.forEach((p,i)=>{const s=tour.stops.filter(x=>Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lng)))[i]; L.marker(p,{poi:true,icon:L.divIcon({className:'poi-marker',html:TYPES[s.type]||'📍',iconSize:[30,30]})}).addTo(map).bindPopup(`<strong>${esc(s.name)}</strong><br>${esc(s.notes||'')}`);}); if(points.length>1) { routeLine=L.polyline(points,{color:'#35e0a1',weight:4,opacity:.85,dashArray:'7 8'}).addTo(map); map.fitBounds(routeLine.getBounds(),{padding:[35,35]}); } else if(points.length) map.setView(points[0],12); }
function startGPS() { if(!navigator.geolocation) return toast('GPS non supportato dal browser'); if(watchId) return; watchId=navigator.geolocation.watchPosition(onPosition,()=>toast('Impossibile leggere il GPS. Controlla i permessi.'),{enableHighAccuracy:true,maximumAge:10000,timeout:15000}); }
function onPosition(pos) { lastPosition=pos; const point=[pos.coords.latitude,pos.coords.longitude]; if(map) { if(!userMarker) userMarker=L.marker(point,{icon:L.divIcon({className:'user-marker',iconSize:[17,17]})}).addTo(map); else userMarker.setLatLng(point); } proximityCheck(pos); updateHud(); }
function proximityCheck(pos) { if(!tour)return; const next=getNextStop(); if(next&&Number.isFinite(Number(next.lat))&&distance(pos.coords.latitude,pos.coords.longitude,next.lat,next.lng)<=250) markReached(true); tour.stops.forEach((s,i)=>{ if(!['drone','photo'].includes(s.type)||alerted.has(i)||!Number.isFinite(Number(s.lat)))return; const d=distance(pos.coords.latitude,pos.coords.longitude,Number(s.lat),Number(s.lng)); if(d<=1000) { alerted.add(i); $('#gpsNotice').textContent=`${TYPES[s.type]} ${s.name} — a ${formatDistance(d)}. ${s.notes||''}`; $('#gpsNotice').hidden=false; navigator.vibrate?.([120,70,120]); setTimeout(()=>$('#gpsNotice').hidden=true,12000); } }); }
function updateHud() { if(!tour){$('#nextStop').textContent='Nessun tour attivo';$('#nextDistance').textContent='Torna a Pianifica per crearne uno';$('#scheduleStatus').textContent='—';return;} const next=getNextStop(); $('#nextStop').textContent=next?.name||'Tour completato'; if(next&&lastPosition&&Number.isFinite(Number(next.lat))) $('#nextDistance').textContent=`${formatDistance(distance(lastPosition.coords.latitude,lastPosition.coords.longitude,next.lat,next.lng))} in linea d’aria`; else $('#nextDistance').textContent=next?.targetTime?`Orario previsto ${displayTargetTime(next.targetTime)}`:'Nessun orario previsto'; if(!tour.realDepartureTime) return $('#scheduleStatus').textContent='Imposta l’orario di partenza reale'; if(!next) return $('#scheduleStatus').textContent='Tour completato'; if(!next.targetTime) return $('#scheduleStatus').textContent='Prossima tappa senza orario target'; const delta=timeMinutes(currentTime())-timeMinutes(displayTargetTime(next.targetTime)); $('#scheduleStatus').textContent=delta>0?`${delta} min oltre l’orario della prossima tappa`:`In tabella · prossima tappa alle ${displayTargetTime(next.targetTime)}`; }
function getNextStop(){ if(!tour)return null; const done=new Set(tour.completedStops||[]); const index=tour.stops.findIndex((_,i)=>!done.has(i)); return index<0?null:{...tour.stops[index],_index:index}; }
function markReached(automatic=false){const next=getNextStop();if(!next)return;tour.completedStops=tour.completedStops||[];tour.completedStops.push(next._index);const target=next.targetTime?displayTargetTime(next.targetTime):null;const delta=target?timeMinutes(currentTime())-timeMinutes(target):null;save();updateHud();toast(delta===null?`${automatic?'GPS: ':''}tappa raggiunta`:delta>0?`${automatic?'GPS: ':''}tappa raggiunta · ${delta} min in ritardo`:`${automatic?'GPS: ':''}tappa raggiunta · ${-delta} min in anticipo`);}
function timeMinutes(t){const [h,m]=t.split(':').map(Number);return h*60+m} function scheduleOffset(){return tour.realDepartureTime&&tour.departureTime?timeMinutes(tour.realDepartureTime)-timeMinutes(tour.departureTime):0} function displayTargetTime(t){if(!t)return '';const m=(timeMinutes(t)+scheduleOffset()+1440)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`} function currentTime(){return new Date().toTimeString().slice(0,5)} function distance(a,b,c,d){if(!Number.isFinite(Number(c)))return NaN;const R=6371000,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180;return 2*R*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2))} function formatDistance(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)} function readFile(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);d=Array.isArray(d)?d[0]:d;if(!Array.isArray(d.stops))throw Error();tour={...d,id:crypto.randomUUID()};tours.push(tour);activeTourId=tour.id;save();toast('Nuovo tour caricato')}catch{toast('Il file non è un itinerario valido')}};r.readAsText(f)} function exportTour(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(tour,null,2)],{type:'application/json'}));a.download='mio-itinerario.json';a.click();URL.revokeObjectURL(a.href)}
init();
